// ANGULAR-LIBRARY/FRONTEND/src/app/modules/library/universes/components/universes/universes.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-universes',
  templateUrl: './universes.component.html',
  styleUrls: ['./universes.component.css']
})
export class UniversesComponent {
@Input() universe: any
}


<div class="universe-container">
  <div style="display: flex; justify-content: flex-end; align-items: center; margin-bottom: 5px; gap: 5px">
      <button [routerLink]="['/admin/edit-product', universe._id]" >Editar</button>
      <button [routerLink]="['/admin/delete-product', universe._id]" >Eliminar</button>
  </div>
  <img [src]="universe.picture" />
  <div class="description-universe">
    <h2 class="short-tittle">{{ universe.nameUniverse }}</h2>
    <p class="short-text">{{ universe.author }}</p>
    <p class="short-text">{{ universe.sagas1 }}</p>
    <p class="short-text">{{ universe.sagas2 }}</p>
    <p class="short-text">{{ universe.sagas3 }}</p>
    <p class="short-text">{{ universe.sagas4 }}</p>
    <p class="short-text">{{ universe.sagas5 }}</p>
    <p class="short-text">{{ universe.sagas6 }}</p>
    <p class="short-text">{{ universe.sagas7 }}</p>
    <p class="short-text">{{ universe.resume }}</p>
  </div>
</div>

// ANGULAR-LIBRARY/FRONTEND-project-react-LUIS/src/components/core/MainPage/MenuUniverse/Universes.jsx
import img from "../../../images/Vacío-6_jh3g7a.jpg"

function Universes({ universe }) {

  return (
    <article className="universeCard">
      <h2 className="nameUniverse">{universe.nameUniverse}</h2>
      <p>{universe.author}</p>
      <p>{universe.sagas1}</p>
      <p>{universe.sagas2}</p>
      <p>{universe.sagas3}</p>
      <p>{universe.sagas4}</p>
      <p>{universe.sagas5}</p>
      <p>{universe.sagas6}</p>
      <p>{universe.sagas7}</p>
      <p className="resume">{universe.resume}</p>
      {universe.picture ? <img className="universe-image" src={universe.picture} alt={`Imagen de ${universe.title}`} /> : <img className="universe-image" src={img} />}
    </article>
  );
}

export default Universes;
